### ISSUE TITLE
Update cadence

### ISSUE THREAD

**Issue by jonmmease** [nteract/minimal-plotly#13]
Hi, plotly.py maintainer here. I ended up in this repo after [learning](https://github.com/Microsoft/vscode-python/issues/4953) that the VSCode Python plugin relies on `@nteract/transform-plotly` for rendering plotly figures, and that `@nteract/transform-plotly` gets it's plotly.js version from the project.

I see that there is a bot generated PR to update this repo with the most recent version of plotly.js at https://github.com/nteract/minimal-plotly/pull/12, but that this update hasn't been applied since December. I was wondering how frequently you aim to merge/publish these plotly.js updates to NPM, and whether this is something that could happen alongside the plotly.js releases themselves.  Thanks!

**Comment by jonmmease** [comment]
Friendly ping @rgbkrk @lgeiger

**Comment by captainsafia** [comment]
Hello @jonmmease! Thank you for being proactive and surfacing this in the Slack team.

I just did a one-off release and bumped this up to 1.47.1. Moving forward, I'll merge the renovate PRs and publish new releases on Monday evenings alongside the release cycle from the nteract monorepo.

**Comment by jonmmease** [comment]
Thank you so much!  I'm very excited for nteract and VSCode to be first-class interfaces for plotly.py users.
