### ISSUE TITLE
Publishing latest release

### ISSUE THREAD

**Issue by nicolaskruchten** [nteract/minimal-plotly#18]
Hello!

https://github.com/nteract/minimal-plotly/pull/16 was merged but not released to NPM, and this is causing some issues with downstream users who are using libraries built on top of Plotly but need a more recent version in their environments...

Could you please release this to NPM? :)

**Comment by nicolaskruchten** [comment]
Actually it's not just #16 that hasn't been published but #15 also, so the currently-published version only has 1.47, and there are some important features in 1.48 that we would really love to make available to all downstream users of this package please! 🙏

**Comment by willingc** [comment]
Hi @nicolaskruchten. While triaging issues for nteract, I saw this open issue. Recently a new release 1.48.3 was made to npm: https://www.npmjs.com/package/@nteract/plotly
