### ISSUE TITLE
Upgrade to latest version of plotly

### ISSUE THREAD

**Issue by rgbkrk** [nteract/minimal-plotly#5]
As surfaced in https://github.com/nteract/nteract/issues/3323, we need to upgrade our plotly. :)

**Comment by jameskoch** [comment]
Is minimal-plotly publishing automatically as described in README? I'm not seeing it at https://www.npmjs.com/package/@nteract/plotly

**Comment by rgbkrk** [comment]
Based on #6 I don't think it was published.

**Comment by rgbkrk** [comment]
@lgeiger is on the case!
